// Code generated by protoc-gen-go. DO NOT EDIT.
// source: egress.proto

package egresspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Reference_Relationship int32

const (
	Reference_CHILD_OF     Reference_Relationship = 0
	Reference_FOLLOWS_FROM Reference_Relationship = 1
)

var Reference_Relationship_name = map[int32]string{
	0: "CHILD_OF",
	1: "FOLLOWS_FROM",
}
var Reference_Relationship_value = map[string]int32{
	"CHILD_OF":     0,
	"FOLLOWS_FROM": 1,
}

func (x Reference_Relationship) String() string {
	return proto.EnumName(Reference_Relationship_name, int32(x))
}
func (Reference_Relationship) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{3, 0}
}

type SpanContext struct {
	TraceId              uint64            `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId               uint64            `protobuf:"varint,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Baggage              map[string]string `protobuf:"bytes,3,rep,name=baggage,proto3" json:"baggage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SpanContext) Reset()         { *m = SpanContext{} }
func (m *SpanContext) String() string { return proto.CompactTextString(m) }
func (*SpanContext) ProtoMessage()    {}
func (*SpanContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{0}
}
func (m *SpanContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpanContext.Unmarshal(m, b)
}
func (m *SpanContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpanContext.Marshal(b, m, deterministic)
}
func (dst *SpanContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpanContext.Merge(dst, src)
}
func (m *SpanContext) XXX_Size() int {
	return xxx_messageInfo_SpanContext.Size(m)
}
func (m *SpanContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SpanContext.DiscardUnknown(m)
}

var xxx_messageInfo_SpanContext proto.InternalMessageInfo

func (m *SpanContext) GetTraceId() uint64 {
	if m != nil {
		return m.TraceId
	}
	return 0
}

func (m *SpanContext) GetSpanId() uint64 {
	if m != nil {
		return m.SpanId
	}
	return 0
}

func (m *SpanContext) GetBaggage() map[string]string {
	if m != nil {
		return m.Baggage
	}
	return nil
}

// Represent both tags and log fields.
type KeyValue struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*KeyValue_StringValue
	//	*KeyValue_IntValue
	//	*KeyValue_DoubleValue
	//	*KeyValue_BoolValue
	//	*KeyValue_JsonValue
	Value                isKeyValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{1}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isKeyValue_Value interface {
	isKeyValue_Value()
}

type KeyValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type KeyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type KeyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type KeyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type KeyValue_JsonValue struct {
	JsonValue []byte `protobuf:"bytes,6,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*KeyValue_StringValue) isKeyValue_Value() {}

func (*KeyValue_IntValue) isKeyValue_Value() {}

func (*KeyValue_DoubleValue) isKeyValue_Value() {}

func (*KeyValue_BoolValue) isKeyValue_Value() {}

func (*KeyValue_JsonValue) isKeyValue_Value() {}

func (m *KeyValue) GetValue() isKeyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*KeyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *KeyValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*KeyValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *KeyValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*KeyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *KeyValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*KeyValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *KeyValue) GetJsonValue() []byte {
	if x, ok := m.GetValue().(*KeyValue_JsonValue); ok {
		return x.JsonValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*KeyValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _KeyValue_OneofMarshaler, _KeyValue_OneofUnmarshaler, _KeyValue_OneofSizer, []interface{}{
		(*KeyValue_StringValue)(nil),
		(*KeyValue_IntValue)(nil),
		(*KeyValue_DoubleValue)(nil),
		(*KeyValue_BoolValue)(nil),
		(*KeyValue_JsonValue)(nil),
	}
}

func _KeyValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*KeyValue)
	// value
	switch x := m.Value.(type) {
	case *KeyValue_StringValue:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *KeyValue_IntValue:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *KeyValue_DoubleValue:
		b.EncodeVarint(4<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *KeyValue_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *KeyValue_JsonValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.JsonValue)
	case nil:
	default:
		return fmt.Errorf("KeyValue.Value has unexpected type %T", x)
	}
	return nil
}

func _KeyValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*KeyValue)
	switch tag {
	case 2: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &KeyValue_StringValue{x}
		return true, err
	case 3: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &KeyValue_IntValue{int64(x)}
		return true, err
	case 4: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &KeyValue_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 5: // value.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &KeyValue_BoolValue{x != 0}
		return true, err
	case 6: // value.json_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &KeyValue_JsonValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _KeyValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*KeyValue)
	// value
	switch x := m.Value.(type) {
	case *KeyValue_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *KeyValue_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *KeyValue_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *KeyValue_BoolValue:
		n += 1 // tag and wire
		n += 1
	case *KeyValue_JsonValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.JsonValue)))
		n += len(x.JsonValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Log struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields               []*KeyValue          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{2}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Log) GetFields() []*KeyValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Reference struct {
	Relationship         Reference_Relationship `protobuf:"varint,1,opt,name=relationship,proto3,enum=lightstep.egress.Reference_Relationship" json:"relationship,omitempty"`
	SpanContext          *SpanContext           `protobuf:"bytes,2,opt,name=span_context,json=spanContext,proto3" json:"span_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{3}
}
func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (dst *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(dst, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetRelationship() Reference_Relationship {
	if m != nil {
		return m.Relationship
	}
	return Reference_CHILD_OF
}

func (m *Reference) GetSpanContext() *SpanContext {
	if m != nil {
		return m.SpanContext
	}
	return nil
}

type StreamInitialization struct {
	ReporterId           uint64      `protobuf:"varint,1,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Tags                 []*KeyValue `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamInitialization) Reset()         { *m = StreamInitialization{} }
func (m *StreamInitialization) String() string { return proto.CompactTextString(m) }
func (*StreamInitialization) ProtoMessage()    {}
func (*StreamInitialization) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{4}
}
func (m *StreamInitialization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInitialization.Unmarshal(m, b)
}
func (m *StreamInitialization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInitialization.Marshal(b, m, deterministic)
}
func (dst *StreamInitialization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInitialization.Merge(dst, src)
}
func (m *StreamInitialization) XXX_Size() int {
	return xxx_messageInfo_StreamInitialization.Size(m)
}
func (m *StreamInitialization) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInitialization.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInitialization proto.InternalMessageInfo

func (m *StreamInitialization) GetReporterId() uint64 {
	if m != nil {
		return m.ReporterId
	}
	return 0
}

func (m *StreamInitialization) GetTags() []*KeyValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Span struct {
	SpanContext          *SpanContext         `protobuf:"bytes,1,opt,name=span_context,json=spanContext,proto3" json:"span_context,omitempty"`
	OperationName        string               `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	References           []*Reference         `protobuf:"bytes,3,rep,name=references,proto3" json:"references,omitempty"`
	StartTimestamp       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	DurationMicros       uint64               `protobuf:"varint,5,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	Tags                 []*KeyValue          `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Logs                 []*Log               `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{5}
}
func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (dst *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(dst, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetSpanContext() *SpanContext {
	if m != nil {
		return m.SpanContext
	}
	return nil
}

func (m *Span) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Span) GetReferences() []*Reference {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Span) GetStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *Span) GetDurationMicros() uint64 {
	if m != nil {
		return m.DurationMicros
	}
	return 0
}

func (m *Span) GetTags() []*KeyValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Span) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Reporter struct {
	ReporterId           uint64      `protobuf:"varint,1,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Tags                 []*KeyValue `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Reporter) Reset()         { *m = Reporter{} }
func (m *Reporter) String() string { return proto.CompactTextString(m) }
func (*Reporter) ProtoMessage()    {}
func (*Reporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{6}
}
func (m *Reporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reporter.Unmarshal(m, b)
}
func (m *Reporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reporter.Marshal(b, m, deterministic)
}
func (dst *Reporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reporter.Merge(dst, src)
}
func (m *Reporter) XXX_Size() int {
	return xxx_messageInfo_Reporter.Size(m)
}
func (m *Reporter) XXX_DiscardUnknown() {
	xxx_messageInfo_Reporter.DiscardUnknown(m)
}

var xxx_messageInfo_Reporter proto.InternalMessageInfo

func (m *Reporter) GetReporterId() uint64 {
	if m != nil {
		return m.ReporterId
	}
	return 0
}

func (m *Reporter) GetTags() []*KeyValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

type MetricsSample struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*MetricsSample_IntValue
	//	*MetricsSample_DoubleValue
	Value                isMetricsSample_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetricsSample) Reset()         { *m = MetricsSample{} }
func (m *MetricsSample) String() string { return proto.CompactTextString(m) }
func (*MetricsSample) ProtoMessage()    {}
func (*MetricsSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{7}
}
func (m *MetricsSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsSample.Unmarshal(m, b)
}
func (m *MetricsSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsSample.Marshal(b, m, deterministic)
}
func (dst *MetricsSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsSample.Merge(dst, src)
}
func (m *MetricsSample) XXX_Size() int {
	return xxx_messageInfo_MetricsSample.Size(m)
}
func (m *MetricsSample) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsSample.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsSample proto.InternalMessageInfo

func (m *MetricsSample) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isMetricsSample_Value interface {
	isMetricsSample_Value()
}

type MetricsSample_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetricsSample_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

func (*MetricsSample_IntValue) isMetricsSample_Value() {}

func (*MetricsSample_DoubleValue) isMetricsSample_Value() {}

func (m *MetricsSample) GetValue() isMetricsSample_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetricsSample) GetIntValue() int64 {
	if x, ok := m.GetValue().(*MetricsSample_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *MetricsSample) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*MetricsSample_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetricsSample) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetricsSample_OneofMarshaler, _MetricsSample_OneofUnmarshaler, _MetricsSample_OneofSizer, []interface{}{
		(*MetricsSample_IntValue)(nil),
		(*MetricsSample_DoubleValue)(nil),
	}
}

func _MetricsSample_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetricsSample)
	// value
	switch x := m.Value.(type) {
	case *MetricsSample_IntValue:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *MetricsSample_DoubleValue:
		b.EncodeVarint(3<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case nil:
	default:
		return fmt.Errorf("MetricsSample.Value has unexpected type %T", x)
	}
	return nil
}

func _MetricsSample_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetricsSample)
	switch tag {
	case 2: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &MetricsSample_IntValue{int64(x)}
		return true, err
	case 3: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &MetricsSample_DoubleValue{math.Float64frombits(x)}
		return true, err
	default:
		return false, nil
	}
}

func _MetricsSample_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetricsSample)
	// value
	switch x := m.Value.(type) {
	case *MetricsSample_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *MetricsSample_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InternalMetrics struct {
	StartTimestamp       *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	DurationMicros       uint64               `protobuf:"varint,2,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	Logs                 []*Log               `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	Counts               []*MetricsSample     `protobuf:"bytes,4,rep,name=counts,proto3" json:"counts,omitempty"`
	Gauges               []*MetricsSample     `protobuf:"bytes,5,rep,name=gauges,proto3" json:"gauges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InternalMetrics) Reset()         { *m = InternalMetrics{} }
func (m *InternalMetrics) String() string { return proto.CompactTextString(m) }
func (*InternalMetrics) ProtoMessage()    {}
func (*InternalMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{8}
}
func (m *InternalMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalMetrics.Unmarshal(m, b)
}
func (m *InternalMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalMetrics.Marshal(b, m, deterministic)
}
func (dst *InternalMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalMetrics.Merge(dst, src)
}
func (m *InternalMetrics) XXX_Size() int {
	return xxx_messageInfo_InternalMetrics.Size(m)
}
func (m *InternalMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_InternalMetrics proto.InternalMessageInfo

func (m *InternalMetrics) GetStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *InternalMetrics) GetDurationMicros() uint64 {
	if m != nil {
		return m.DurationMicros
	}
	return 0
}

func (m *InternalMetrics) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *InternalMetrics) GetCounts() []*MetricsSample {
	if m != nil {
		return m.Counts
	}
	return nil
}

func (m *InternalMetrics) GetGauges() []*MetricsSample {
	if m != nil {
		return m.Gauges
	}
	return nil
}

type Auth struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{9}
}
func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (dst *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(dst, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ReportRequest struct {
	Reporter              *Reporter        `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	Auth                  *Auth            `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Spans                 []*Span          `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	TimestampOffsetMicros int64            `protobuf:"varint,5,opt,name=timestamp_offset_micros,json=timestampOffsetMicros,proto3" json:"timestamp_offset_micros,omitempty"`
	InternalMetrics       *InternalMetrics `protobuf:"bytes,6,opt,name=internal_metrics,json=internalMetrics,proto3" json:"internal_metrics,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{10}
}
func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (dst *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(dst, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *ReportRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ReportRequest) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *ReportRequest) GetTimestampOffsetMicros() int64 {
	if m != nil {
		return m.TimestampOffsetMicros
	}
	return 0
}

func (m *ReportRequest) GetInternalMetrics() *InternalMetrics {
	if m != nil {
		return m.InternalMetrics
	}
	return nil
}

type Command struct {
	Disable              bool     `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{11}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

type ReportResponse struct {
	Commands             []*Command           `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	ReceiveTimestamp     *timestamp.Timestamp `protobuf:"bytes,2,opt,name=receive_timestamp,json=receiveTimestamp,proto3" json:"receive_timestamp,omitempty"`
	TransmitTimestamp    *timestamp.Timestamp `protobuf:"bytes,3,opt,name=transmit_timestamp,json=transmitTimestamp,proto3" json:"transmit_timestamp,omitempty"`
	Warnings             []string             `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Infos                []string             `protobuf:"bytes,6,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_egress_d120650181a1ca24, []int{12}
}
func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (dst *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(dst, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

func (m *ReportResponse) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *ReportResponse) GetReceiveTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.ReceiveTimestamp
	}
	return nil
}

func (m *ReportResponse) GetTransmitTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.TransmitTimestamp
	}
	return nil
}

func (m *ReportResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *ReportResponse) GetInfos() []string {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*SpanContext)(nil), "lightstep.egress.SpanContext")
	proto.RegisterMapType((map[string]string)(nil), "lightstep.egress.SpanContext.BaggageEntry")
	proto.RegisterType((*KeyValue)(nil), "lightstep.egress.KeyValue")
	proto.RegisterType((*Log)(nil), "lightstep.egress.Log")
	proto.RegisterType((*Reference)(nil), "lightstep.egress.Reference")
	proto.RegisterType((*StreamInitialization)(nil), "lightstep.egress.StreamInitialization")
	proto.RegisterType((*Span)(nil), "lightstep.egress.Span")
	proto.RegisterType((*Reporter)(nil), "lightstep.egress.Reporter")
	proto.RegisterType((*MetricsSample)(nil), "lightstep.egress.MetricsSample")
	proto.RegisterType((*InternalMetrics)(nil), "lightstep.egress.InternalMetrics")
	proto.RegisterType((*Auth)(nil), "lightstep.egress.Auth")
	proto.RegisterType((*ReportRequest)(nil), "lightstep.egress.ReportRequest")
	proto.RegisterType((*Command)(nil), "lightstep.egress.Command")
	proto.RegisterType((*ReportResponse)(nil), "lightstep.egress.ReportResponse")
	proto.RegisterEnum("lightstep.egress.Reference_Relationship", Reference_Relationship_name, Reference_Relationship_value)
}

func init() { proto.RegisterFile("egress.proto", fileDescriptor_egress_d120650181a1ca24) }

var fileDescriptor_egress_d120650181a1ca24 = []byte{
	// 974 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0x7a, 0x37, 0xf6, 0xfa, 0x79, 0x9b, 0xb8, 0xa3, 0xfe, 0x70, 0x83, 0xaa, 0xb8, 0x1b,
	0x21, 0xdc, 0x0a, 0x6d, 0x25, 0x23, 0x4a, 0x55, 0x2e, 0x90, 0x94, 0x10, 0x83, 0x43, 0xa4, 0x49,
	0x05, 0x12, 0x1c, 0xac, 0xf1, 0x7a, 0xbc, 0x19, 0xba, 0x3b, 0xb3, 0xcc, 0x8c, 0x0b, 0xe1, 0xdf,
	0xe0, 0xca, 0x9d, 0x3f, 0x84, 0x23, 0x17, 0xfe, 0x19, 0xee, 0x68, 0x67, 0x76, 0xd7, 0x4e, 0x6d,
	0x35, 0x41, 0xe2, 0xb6, 0xef, 0xcd, 0xf7, 0xcd, 0x9b, 0x79, 0xdf, 0xf7, 0xc6, 0x86, 0x80, 0x26,
	0x92, 0x2a, 0x15, 0xe5, 0x52, 0x68, 0x81, 0xba, 0x29, 0x4b, 0x2e, 0xb4, 0xd2, 0x34, 0x8f, 0x6c,
	0x7e, 0x6f, 0x3f, 0x11, 0x22, 0x49, 0xe9, 0x53, 0xb3, 0x3e, 0x5d, 0xcc, 0x9f, 0x6a, 0x96, 0x51,
	0xa5, 0x49, 0x96, 0x5b, 0x4a, 0xf8, 0xa7, 0x03, 0x9d, 0xf3, 0x9c, 0xf0, 0x23, 0xc1, 0x35, 0xfd,
	0x45, 0xa3, 0x07, 0xe0, 0x6b, 0x49, 0x62, 0x3a, 0x61, 0xb3, 0x9e, 0xd3, 0x77, 0x06, 0x1e, 0x6e,
	0x99, 0x78, 0x34, 0x43, 0xf7, 0xa1, 0xa5, 0x72, 0xc2, 0x8b, 0x95, 0x86, 0x59, 0x69, 0x16, 0xe1,
	0x68, 0x86, 0x5e, 0x42, 0x6b, 0x4a, 0x92, 0x84, 0x24, 0xb4, 0xe7, 0xf6, 0xdd, 0x41, 0x67, 0xf8,
	0x24, 0x7a, 0xfb, 0x20, 0xd1, 0x4a, 0x8d, 0xe8, 0xd0, 0x82, 0xbf, 0xe0, 0x5a, 0x5e, 0xe2, 0x8a,
	0xba, 0xf7, 0x02, 0x82, 0xd5, 0x05, 0xd4, 0x05, 0xf7, 0x35, 0xbd, 0x34, 0x87, 0x68, 0xe3, 0xe2,
	0x13, 0xdd, 0x81, 0xed, 0x37, 0x24, 0x5d, 0x50, 0x53, 0xbe, 0x8d, 0x6d, 0xf0, 0xa2, 0xf1, 0xdc,
	0x09, 0xff, 0x76, 0xc0, 0xff, 0x9a, 0x5e, 0x7e, 0x5b, 0x24, 0x36, 0x10, 0x0f, 0x20, 0x50, 0x5a,
	0x32, 0x9e, 0x4c, 0x56, 0xf8, 0x27, 0x5b, 0xb8, 0x63, 0xb3, 0x96, 0xf6, 0x10, 0xda, 0x8c, 0xeb,
	0x12, 0xe1, 0xf6, 0x9d, 0x81, 0x7b, 0xb2, 0x85, 0x7d, 0xc6, 0xb5, 0x5d, 0x3e, 0x80, 0x60, 0x26,
	0x16, 0xd3, 0x94, 0x96, 0x08, 0xaf, 0xef, 0x0c, 0x9c, 0x62, 0x0f, 0x9b, 0xb5, 0xa0, 0x7d, 0x80,
	0xa9, 0x10, 0x69, 0x09, 0xd9, 0xee, 0x3b, 0x03, 0xff, 0x64, 0x0b, 0xb7, 0x8b, 0x5c, 0x0d, 0xf8,
	0x51, 0x09, 0x5e, 0x02, 0x9a, 0x7d, 0x67, 0x10, 0x14, 0x80, 0x22, 0x67, 0x00, 0x87, 0xad, 0xf2,
	0x8e, 0xa1, 0x02, 0x77, 0x2c, 0x12, 0xf4, 0x1c, 0xda, 0xb5, 0x64, 0xe6, 0x4a, 0x9d, 0xe1, 0x5e,
	0x64, 0x45, 0x8d, 0x2a, 0x51, 0xa3, 0x57, 0x15, 0x02, 0x2f, 0xc1, 0x68, 0x08, 0xcd, 0x39, 0xa3,
	0xe9, 0x4c, 0xf5, 0x1a, 0x46, 0x94, 0xbd, 0x75, 0x51, 0xaa, 0x96, 0xe1, 0x12, 0x19, 0xfe, 0xe5,
	0x40, 0x1b, 0xd3, 0x39, 0x95, 0x94, 0xc7, 0x14, 0x8d, 0x21, 0x90, 0x34, 0x25, 0x9a, 0x09, 0xae,
	0x2e, 0x98, 0x2d, 0xbf, 0x33, 0x1c, 0xac, 0xef, 0x53, 0x53, 0x22, 0xbc, 0x82, 0xc7, 0x57, 0xd8,
	0xe8, 0x33, 0x08, 0x8c, 0x7d, 0x62, 0xeb, 0x02, 0x23, 0x42, 0x67, 0xf8, 0xf0, 0x9d, 0x56, 0xc1,
	0x1d, 0xb5, 0x0c, 0xc2, 0x08, 0x82, 0xd5, 0xfd, 0x51, 0x00, 0xfe, 0xd1, 0xc9, 0x68, 0xfc, 0x72,
	0x72, 0x76, 0xdc, 0xdd, 0x42, 0x5d, 0x08, 0x8e, 0xcf, 0xc6, 0xe3, 0xb3, 0xef, 0xce, 0x27, 0xc7,
	0xf8, 0xec, 0xb4, 0xeb, 0x84, 0x09, 0xdc, 0x39, 0xd7, 0x92, 0x92, 0x6c, 0xc4, 0x99, 0x66, 0x24,
	0x65, 0xbf, 0x1a, 0x2e, 0xda, 0x87, 0x8e, 0xa4, 0xb9, 0x90, 0x9a, 0xca, 0xa5, 0xcd, 0xa1, 0x4a,
	0x8d, 0x66, 0x28, 0x02, 0x4f, 0x93, 0xe4, 0x26, 0x8d, 0x33, 0xb8, 0xf0, 0x9f, 0x06, 0x78, 0xc5,
	0xa9, 0xd7, 0xee, 0xe8, 0xfc, 0xd7, 0x3b, 0xa2, 0xf7, 0x61, 0x47, 0xe4, 0x54, 0x9a, 0x83, 0x4e,
	0x38, 0xc9, 0x2a, 0xb3, 0xdf, 0xaa, 0xb3, 0xdf, 0x90, 0x8c, 0xa2, 0x4f, 0x01, 0x64, 0xd5, 0x74,
	0x55, 0x4e, 0xdd, 0x7b, 0xef, 0x10, 0x06, 0xaf, 0xc0, 0xd1, 0x11, 0xec, 0x2a, 0x4d, 0xa4, 0x9e,
	0x2c, 0x9d, 0xe5, 0x5d, 0xeb, 0xac, 0x1d, 0x43, 0xa9, 0x63, 0xf4, 0x01, 0xec, 0xce, 0x16, 0xe5,
	0x39, 0x33, 0x16, 0x4b, 0xa1, 0x8c, 0xdf, 0x3d, 0xbc, 0x53, 0xa5, 0x4f, 0x4d, 0xb6, 0x6e, 0x66,
	0xf3, 0x66, 0xcd, 0x44, 0x8f, 0xc1, 0x4b, 0x45, 0xa2, 0x7a, 0x2d, 0x83, 0xbf, 0xbb, 0x8e, 0x1f,
	0x8b, 0x04, 0x1b, 0x48, 0xf8, 0x03, 0xf8, 0xb8, 0x54, 0xed, 0xe6, 0xa2, 0x7a, 0x37, 0x14, 0x35,
	0x87, 0x5b, 0xa7, 0x54, 0x4b, 0x16, 0xab, 0x73, 0x92, 0xe5, 0x29, 0x45, 0x08, 0x3c, 0x23, 0x88,
	0x7d, 0x58, 0xcc, 0xf7, 0xd5, 0x47, 0xa3, 0x71, 0xed, 0xa3, 0xe1, 0x6e, 0x78, 0x34, 0x96, 0x23,
	0xff, 0x7b, 0x03, 0x76, 0x47, 0x5c, 0x53, 0xc9, 0x49, 0x5a, 0x96, 0xde, 0xa4, 0x95, 0xf3, 0x7f,
	0x68, 0xd5, 0xd8, 0xa8, 0x55, 0xd5, 0x7b, 0xf7, 0xda, 0xde, 0xa3, 0x4f, 0xa0, 0x19, 0x8b, 0x05,
	0xd7, 0x55, 0x43, 0xf7, 0xd7, 0xc1, 0x57, 0xda, 0x87, 0x4b, 0x78, 0x41, 0x4c, 0xc8, 0x22, 0xa1,
	0x85, 0x5f, 0x6e, 0x46, 0xb4, 0xf0, 0xf0, 0x31, 0x78, 0x9f, 0x2f, 0xf4, 0x05, 0x7a, 0x04, 0x01,
	0x89, 0x63, 0xaa, 0xd4, 0x44, 0x8b, 0xd7, 0x94, 0x97, 0x7a, 0x74, 0x6c, 0xee, 0x55, 0x91, 0x0a,
	0xff, 0x68, 0xc0, 0x2d, 0xeb, 0x0c, 0x4c, 0x7f, 0x5a, 0x50, 0xa5, 0xd1, 0x33, 0xf0, 0x2b, 0x2f,
	0xd4, 0x0d, 0xdc, 0x30, 0x2e, 0x16, 0x81, 0x6b, 0x2c, 0x7a, 0x02, 0x1e, 0x59, 0xe8, 0x8b, 0xf2,
	0xb5, 0xba, 0xb7, 0xce, 0x29, 0x8e, 0x84, 0x0d, 0x06, 0x7d, 0x08, 0xdb, 0xc5, 0x28, 0x57, 0xed,
	0xbb, 0xb7, 0x79, 0xec, 0xb1, 0x05, 0xa1, 0x67, 0x70, 0xbf, 0xd6, 0x74, 0x22, 0xe6, 0x73, 0x45,
	0xf5, 0xea, 0x20, 0xb9, 0xf8, 0x6e, 0xbd, 0x7c, 0x66, 0x56, 0x4b, 0x8d, 0xc6, 0xd0, 0x65, 0xa5,
	0x49, 0x26, 0x99, 0x6d, 0x94, 0xf9, 0x21, 0xe9, 0x0c, 0x1f, 0xad, 0x17, 0x7c, 0xcb, 0x4e, 0x78,
	0x97, 0x5d, 0x4d, 0x84, 0x07, 0xd0, 0x3a, 0x12, 0x59, 0x46, 0xf8, 0x0c, 0xf5, 0xa0, 0x35, 0x63,
	0x8a, 0x4c, 0x53, 0x6b, 0x71, 0x1f, 0x57, 0x61, 0xf8, 0x5b, 0x03, 0x76, 0xaa, 0x76, 0xaa, 0x5c,
	0x70, 0x45, 0xd1, 0xc7, 0xe0, 0xc7, 0x96, 0xa7, 0x7a, 0x8e, 0xb9, 0xee, 0x83, 0xf5, 0xea, 0xe5,
	0xce, 0xb8, 0x86, 0xa2, 0x2f, 0xe1, 0xb6, 0xa4, 0x31, 0x65, 0x6f, 0xe8, 0x8a, 0xa1, 0x1b, 0xd7,
	0x1a, 0xba, 0x5b, 0x92, 0x96, 0x96, 0x1e, 0x01, 0xd2, 0x92, 0x70, 0x95, 0xb1, 0xd5, 0xd1, 0x70,
	0xaf, 0xdd, 0xe9, 0x76, 0xc5, 0x5a, 0x6e, 0xb5, 0x07, 0xfe, 0xcf, 0x44, 0x72, 0xc6, 0x13, 0x6b,
	0xc9, 0x36, 0xae, 0xe3, 0xe2, 0x2f, 0x07, 0xe3, 0x73, 0x61, 0x5f, 0xaf, 0x36, 0xb6, 0xc1, 0x57,
	0x9e, 0xef, 0x75, 0xb7, 0x0f, 0xe1, 0x7b, 0xdf, 0xde, 0x33, 0x9f, 0x4e, 0x9b, 0xa6, 0xd4, 0x47,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x7a, 0xe5, 0xad, 0x90, 0x09, 0x00, 0x00,
}
